Update services-start

diff --git a/release/src/router/custom-scripts/services-start b/release/src/router/custom-scripts/services-start
--- a/release/src/router/custom-scripts/services-start
+++ b/release/src/router/custom-scripts/services-start
@@ -91,7 +91,7 @@ echo "ethtool --set-tunable $usb_interface rx-copybreak 256: $( [ $? -eq 0 ] && 
 ethtool -A $usb_interface rx off tx off
 # Enable flow control
 # ethtool -A $usb_interface rx on tx off
-echo "ethtool -A $usb_interface rx off tx off (Disable flow control): $( [ $? -eq 0 ] && echo 'OK (0)' || echo 'ERROR ($?)' )" >> /tmp/001-services-start
+echo "ethtool -A $usb_interface rx off tx off: $( [ $? -eq 0 ] && echo 'OK (0)' || echo 'ERROR ($?)' )" >> /tmp/001-services-start
 
 # Restart the USB interface to apply changes
 ifconfig $usb_interface down && ifconfig $usb_interface up
